### ISSUE TITLE
How to update only one language

### ISSUE THREAD

**Issue by forcewill** [mehalick/OrangeJetpack.Localization#5]
Hi great work however i am facing a difficulty using `OrangeJetpack.Localization` i am sending to my frontend the localized object, and the frontend will send an PUT/POST request meaning i will only update some localized properties for a specific language i tried to do it like this:

 ```
           var state = db.States.FirstOrDefault(s => s.Id == st.Id);

           
            LocalizedContent[] name = {
                new LocalizedContent(lang, st.Name), 
            };


            state.Set(p => p.Name, name);


            AddOrUpdate(db, state);

            db.SaveChanges();
```

however this approach will remove any other languages from the Name attribute json 

maybe add a version of set like 
`Set(property, value, lang) `that would replace only that value on the json dictionary would be enough

**Comment by forcewill** [comment]
managed to solve it like this 

        

            var state = db.States.FirstOrDefault(s => s.Id == st.Id);

            LocalizedContent[] names = LocalizedContent.Deserialize(state.Name);

            LocalizedContent name = names.FirstOrDefault(p => p.Key.Equals(lang));


            name.Value = st.Name;

            state.Set(p => p.Name, names);


            AddOrUpdate(db, state);

            db.SaveChanges();


Are you willing to accept pull requests ?

**Comment by mehalick** [comment]
@forcewill Your solution is exactly how I would do it,.. but I also agree that a `Set(property, value, lang)` overload is a great idea as I suspect your use case would be a common one for others.

If you're willing to submit a pull request I'll gladly review and consider accepting. If you're comfortable with your workaround for the time being I might add this myself in the next release.

Thanks for the interest and for submitting your issue, I really appreciate the feedback.

**Comment by forcewill** [comment]
@mehalick sure, i will do a PR, another method i am just in the process of finishing, is the ability to provide two objects lets assume A is our EF object and B is our DTO i have a 
`A.SetAllFrom(B, lang)`  which uses reflection to look on A for properties marked with the `LocalizedAttribute` and looks for the same names on B settings A properties with B properties for the `lang` passed if you thinks thats also interesting to have i can do a separated PR for that also (however my C# reflection skills are not very good it would be nice if you could review it) i can do both later this week probably
