### ISSUE TITLE
Administration

### ISSUE THREAD

**Issue by CodeLikeAManiac** [mehalick/OrangeJetpack.Localization#9]
I have developed a grid for administrating the objects stored in the database but because the binding is done programmatic  (for every row I am deciding which element to show in which column)  it becomes slow on large data-sets or during refresh.

Have you done anything similar ?

![adminlang](https://user-images.githubusercontent.com/39524062/40554380-332bf50e-604e-11e8-83ce-71d9803ca17b.png)

**Comment by mehalick** [comment]
Thanks for the feedback. If it helps I can send a sample set of admin pages; localization happens in-memory and across 50+ apps over the last 10 years I haven't seen any performance issues.

Aside, if you'd like to check out the latest version we did a complete re-branding and re-write on .NET Standard (works with ASP.NET Core and full framework ASP.NET MVC) see [Xaki](https://xaki.io).
